### ISSUE TITLE
Not logging any events

### ISSUE THREAD

**Issue by AriaFantom** [spec-tacles/gateway#11]
![image](https://user-images.githubusercontent.com/55119711/160273297-ca19eae0-bc56-4109-a810-f912b44f8358.png)
I typed out a message join voice channel tried every events as mentioned but that didn't worked

**Comment by appellation** [comment]
If you're looking to see console output for each event, make sure you have log level set to debug.

**Comment by AriaFantom** [comment]
I have run the code in docker i think logs are default?

**Comment by appellation** [comment]
Log level defaults to info https://github.com/spec-tacles/gateway#usage

**Comment by AriaFantom** [comment]
How can i setup the log level in the command line of docker run command

**Comment by appellation** [comment]
Please refer to Docker documentation https://docs.docker.com/engine/reference/commandline/run/
