### ISSUE TITLE
Add a support for state cache

### ISSUE THREAD

**Issue by AriaFantom** [spec-tacles/gateway#14]
Like there will be cache on redis about each server member and cache will be updated by discord events like guildmember add/remove/update - Which can allow us to bypass the the special intent feature introduce by discord as of we just fetch data from our cache and get any member details or there presence data ;)

**Comment by appellation** [comment]
Cache is definitely something I've thought about, but its complexity and scope has prevented me from implementing a satisfactory solution. Perhaps at some point in the future, but I wouldn't hold my breath on it.
