### ISSUE TITLE
Support for `resume_gateway_url`

### ISSUE THREAD

**Issue by TheNoob27** [spec-tacles/gateway#16]
`resume_gateway_url` has been out for websocket connections to use for a while now, do you plan on adding support for it?

**Comment by appellation** [comment]
I have no current plans since most of my effort went into spec-tacles/spectacles and the new implementations there. However, I will leave this open as a reminder/encouragement for anyone else who's interested to add support for it.

**Comment by infinitytmbots** [comment]
Closed with #19
