### ISSUE TITLE
Guild, channel, role cache

### ISSUE THREAD

**Issue by xSke** [spec-tacles/gateway#9]
How does the gateway handle this, if at all? Discord bots generally need information about the relevant guilds, channels, and roles, in order to do the appropriate permission checking. With a broker like this, it's necessary to store this information in an external cache (eg. Redis) to avoid losing the information upon the consumer reconnecting, since it's only provided by Discord at shard connect time (as part of the `GUILD_CREATE` events). Is there a solution for this in the Spectacles ecosystem at the moment?

**Comment by tbnritzdoge** [comment]
You have to handle the caching by yourself, whilst the spectacles team has no cache implementation by itself it's not too hard to make your own system or implement a djs style of cache. I personally have two workers running, one of which that does bot stuff and the other handles caching and listens to all events emitted by the gateway.

**Comment by appellation** [comment]
There are plans to integrate caching into the proxy. In the meantime, you should use the REST API and cache as necessary. We don't have an existing system in place to do this, but it wouldn't be complicated to set something up for your own specific use case.

**Comment by xSke** [comment]
Alright, thanks :) was mostly just curious.
